-- Generated by scripts/update-registry.mjs from arborist-ts/arborist.nvim/registry.
-- Do not edit manually.
return {
  ["ada"] = {
    install_info = {
      url = "https://github.com/briot/tree-sitter-ada",
      revision = "6b58259a08b1a22ba0247a7ce30be384db618da6",
    },
    maintainers = { "@briot" },
  },
  ["agda"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-agda",
      revision = "e8d47a6987effe34d5595baf321d82d3519a8527",
    },
    maintainers = { "@Decodetalkers" },
  },
  ["angular"] = {
    install_info = {
      url = "https://github.com/dlvandenberg/tree-sitter-angular",
      revision = "f0d0685701b70883fa2dfe94ee7dc27965cab841",
    },
    maintainers = { "@dlvandenberg" },
    requires = { "html", "html_tags" },
  },
  ["apex"] = {
    install_info = {
      url = "https://github.com/aheber/tree-sitter-sfapex",
      location = "apex",
      revision = "3597575a429766dd7ecce9f5bb97f6fec4419d5d",
    },
    maintainers = { "@aheber", "@xixiafinland" },
  },
  ["arduino"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-arduino",
      revision = "11dd46c9ae25135c473c0003a133bb06a484af0c",
    },
    maintainers = { "@ObserverOfTime" },
    requires = { "cpp" },
  },
  ["asm"] = {
    install_info = {
      url = "https://github.com/RubixDev/tree-sitter-asm",
      revision = "839741fef4dab5128952334624905c82b40c7133",
    },
    maintainers = { "@RubixDev" },
  },
  ["astro"] = {
    install_info = {
      url = "https://github.com/virchau13/tree-sitter-astro",
      revision = "213f6e6973d9b456c6e50e86f19f66877e7ef0ee",
    },
    maintainers = { "@virchau13" },
    requires = { "html", "html_tags" },
  },
  ["authzed"] = {
    install_info = {
      url = "https://github.com/mleonidas/tree-sitter-authzed",
      revision = "83e5c26a8687eb4688fe91d690c735cc3d21ad81",
    },
    maintainers = { "@mattpolzin" },
  },
  ["awk"] = {
    install_info = {
      url = "https://github.com/Beaglefoot/tree-sitter-awk",
      revision = "34bbdc7cce8e803096f47b625979e34c1be38127",
    },
  },
  ["bash"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-bash",
      revision = "a06c2e4415e9bc0346c6b86d401879ffb44058f7",
    },
    maintainers = { "@TravonteD" },
  },
  ["bass"] = {
    install_info = {
      url = "https://github.com/vito/tree-sitter-bass",
      revision = "28dc7059722be090d04cd751aed915b2fee2f89a",
    },
    maintainers = { "@amaanq" },
  },
  ["beancount"] = {
    install_info = {
      url = "https://github.com/polarmutex/tree-sitter-beancount",
      revision = "429cff869513cf9e34a2cf604fbfaaedc467e809",
    },
    maintainers = { "@polarmutex" },
  },
  ["bibtex"] = {
    install_info = {
      url = "https://github.com/latex-lsp/tree-sitter-bibtex",
      revision = "8d04ed27b3bc7929f14b7df9236797dab9f3fa66",
    },
    maintainers = { "@theHamsta", "@clason" },
  },
  ["bicep"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-bicep",
      revision = "bff59884307c0ab009bd5e81afd9324b46a6c0f9",
    },
    maintainers = { "@amaanq" },
  },
  ["bitbake"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-bitbake",
      revision = "a5d04fdb5a69a02b8fa8eb5525a60dfb5309b73b",
    },
    maintainers = { "@amaanq" },
  },
  ["blade"] = {
    install_info = {
      url = "https://github.com/EmranMR/tree-sitter-blade",
      revision = "b9436b7b936907aff730de0dac1b99d7c632cc86",
    },
    maintainers = { "@calebdw" },
  },
  ["bp"] = {
    install_info = {
      url = "https://github.com/ambroisie/tree-sitter-bp",
      revision = "ee641d15390183d7535777947ce0f2f1fbcee69f",
    },
    maintainers = { "@ambroisie" },
    readme_note = "Android Blueprint",
  },
  ["bpftrace"] = {
    install_info = {
      url = "https://github.com/sgruszka/tree-sitter-bpftrace",
      revision = "774f4458ad39691336ead1ee361b22434c4cdec7",
    },
    maintainers = { "@sgruszka" },
  },
  ["brightscript"] = {
    install_info = {
      url = "https://github.com/ajdelcimmuto/tree-sitter-brightscript",
      revision = "253fdfaa23814cb46c2d5fc19049fa0f2f62c6da",
    },
    maintainers = { "@ajdelcimmuto" },
  },
  ["c"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-c",
      revision = "ae19b676b13bdcc13b7665397e6d9b14975473dd",
    },
    maintainers = { "@amaanq" },
  },
  ["c3"] = {
    install_info = {
      url = "https://github.com/c3lang/tree-sitter-c3",
      revision = "78e2ae9cff29ef8ca6666006abe80f1236d42996",
    },
    maintainers = { "@cbuttner" },
  },
  ["c_sharp"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-c-sharp",
      revision = "88366631d598ce6595ec655ce1591b315cffb14c",
    },
    maintainers = { "@amaanq" },
  },
  ["caddy"] = {
    install_info = {
      url = "https://github.com/opa-oz/tree-sitter-caddy",
      revision = "2686186edb61be47960431c93a204fb249681360",
    },
  },
  ["cairo"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-cairo",
      revision = "6238f609bea233040fe927858156dee5515a0745",
    },
    maintainers = { "@amaanq" },
  },
  ["capnp"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-capnp",
      revision = "7b0883c03e5edd34ef7bcf703194204299d7099f",
    },
    maintainers = { "@amaanq" },
  },
  ["chatito"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-chatito",
      revision = "c0ed82c665b732395073f635c74c300f09530a7f",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["circom"] = {
    install_info = {
      url = "https://github.com/Decurity/tree-sitter-circom",
      revision = "02150524228b1e6afef96949f2d6b7cc0aaf999e",
    },
    maintainers = { "@alexandr-martirosyan" },
  },
  ["clojure"] = {
    install_info = {
      url = "https://github.com/sogaiu/tree-sitter-clojure",
      revision = "e43eff80d17cf34852dcd92ca5e6986d23a7040f",
    },
    maintainers = { "@NoahTheDuke" },
  },
  ["cmake"] = {
    install_info = {
      url = "https://github.com/uyha/tree-sitter-cmake",
      revision = "c7b2a71e7f8ecb167fad4c97227c838439280175",
    },
    maintainers = { "@uyha" },
  },
  ["comment"] = {
    install_info = {
      url = "https://github.com/stsewd/tree-sitter-comment",
      revision = "66272d2b6c73fb61157541b69dd0a7ce7b42a5ad",
    },
    maintainers = { "@stsewd" },
  },
  ["commonlisp"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-commonlisp",
      revision = "32323509b3d9fe96607d151c2da2c9009eb13a2f",
    },
    maintainers = { "@theHamsta" },
  },
  ["cooklang"] = {
    install_info = {
      url = "https://github.com/addcninblue/tree-sitter-cooklang",
      revision = "4ebe237c1cf64cf3826fc249e9ec0988fe07e58e",
    },
    maintainers = { "@addcninblue" },
  },
  ["corn"] = {
    install_info = {
      url = "https://github.com/jakestanger/tree-sitter-corn",
      revision = "464654742cbfd3a3de560aba120998f1d5dfa844",
    },
    maintainers = { "@jakestanger" },
  },
  ["cpon"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-cpon",
      revision = "594289eadfec719198e560f9d7fd243c4db678d5",
    },
    maintainers = { "@amaanq" },
  },
  ["cpp"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-cpp",
      revision = "8b5b49eb196bec7040441bee33b2c9a4838d6967",
    },
    maintainers = { "@theHamsta" },
    requires = { "c" },
  },
  ["css"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-css",
      revision = "dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f",
    },
    maintainers = { "@TravonteD" },
  },
  ["csv"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-csv",
      location = "csv",
      revision = "f6bf6e35eb0b95fbadea4bb39cb9709507fcb181",
    },
    maintainers = { "@amaanq" },
    requires = { "tsv" },
  },
  ["cuda"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-cuda",
      revision = "48b066f334f4cf2174e05a50218ce2ed98b6fd01",
    },
    maintainers = { "@theHamsta" },
    requires = { "cpp" },
  },
  ["cue"] = {
    install_info = {
      url = "https://github.com/eonpatapon/tree-sitter-cue",
      revision = "20bb9195dac00b64c00ee494812abf3bf76f4181",
    },
    maintainers = { "@amaanq" },
  },
  ["cylc"] = {
    install_info = {
      url = "https://github.com/elliotfontaine/tree-sitter-cylc",
      revision = "6d1d81137112299324b526477ce1db989ab58fb8",
    },
    maintainers = { "@elliotfontaine" },
  },
  ["d"] = {
    install_info = {
      url = "https://github.com/gdamore/tree-sitter-d",
      revision = "fb028c8f14f4188286c2eef143f105def6fbf24f",
    },
    maintainers = { "@amaanq" },
  },
  ["dart"] = {
    install_info = {
      url = "https://github.com/UserNobody14/tree-sitter-dart",
      revision = "0fc19c3a57b1109802af41d2b8f60d8835c5da3a",
    },
    maintainers = { "@akinsho" },
  },
  ["desktop"] = {
    install_info = {
      url = "https://github.com/ValdezFOmar/tree-sitter-desktop",
      revision = "v1.1.1",
    },
    maintainers = { "@ValdezFOmar" },
  },
  ["devicetree"] = {
    install_info = {
      url = "https://github.com/joelspadin/tree-sitter-devicetree",
      revision = "e685f1f6ac1702b046415efb476444167d63e41a",
    },
    maintainers = { "@jedrzejboczar" },
  },
  ["dhall"] = {
    install_info = {
      url = "https://github.com/jbellerb/tree-sitter-dhall",
      revision = "62013259b26ac210d5de1abf64cf1b047ef88000",
    },
    maintainers = { "@amaanq" },
  },
  ["diff"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-diff",
      revision = "2520c3f934b3179bb540d23e0ef45f75304b5fed",
    },
    maintainers = { "@gbprod" },
  },
  ["disassembly"] = {
    install_info = {
      url = "https://github.com/ColinKennedy/tree-sitter-disassembly",
      revision = "0229c0211dba909c5d45129ac784a3f4d49c243a",
    },
    maintainers = { "@ColinKennedy" },
  },
  ["djot"] = {
    install_info = {
      url = "https://github.com/treeman/tree-sitter-djot",
      revision = "74fac1f53c6d52aeac104b6874e5506be6d0cfe6",
    },
    maintainers = { "@NoahTheDuke" },
  },
  ["dockerfile"] = {
    install_info = {
      url = "https://github.com/camdencheek/tree-sitter-dockerfile",
      revision = "971acdd908568b4531b0ba28a445bf0bb720aba5",
    },
    maintainers = { "@camdencheek" },
  },
  ["dot"] = {
    install_info = {
      url = "https://github.com/rydesun/tree-sitter-dot",
      revision = "80327abbba6f47530edeb0df9f11bd5d5c93c14d",
    },
    maintainers = { "@rydesun" },
  },
  ["doxygen"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-doxygen",
      revision = "ccd998f378c3f9345ea4eeb223f56d7b84d16687",
    },
    maintainers = { "@amaanq" },
  },
  ["dtd"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-xml",
      location = "dtd",
      revision = "5000ae8f22d11fbe93939b05c1e37cf21117162d",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["earthfile"] = {
    install_info = {
      url = "https://github.com/glehmann/tree-sitter-earthfile",
      revision = "5baef88717ad0156fd29a8b12d0d8245bb1096a8",
    },
    maintainers = { "@glehmann" },
  },
  ["ebnf"] = {
    install_info = {
      url = "https://github.com/RubixDev/ebnf",
      location = "crates/tree-sitter-ebnf",
      revision = "8e635b0b723c620774dfb8abf382a7f531894b40",
    },
    maintainers = { "@RubixDev" },
  },
  ["editorconfig"] = {
    install_info = {
      url = "https://github.com/ValdezFOmar/tree-sitter-editorconfig",
      revision = "v2.0.0",
    },
    maintainers = { "@ValdezFOmar" },
  },
  ["eds"] = {
    install_info = {
      url = "https://github.com/uyha/tree-sitter-eds",
      revision = "26d529e6cfecde391a03c21d1474eb51e0285805",
    },
    maintainers = { "@uyha" },
  },
  ["eex"] = {
    install_info = {
      url = "https://github.com/connorlay/tree-sitter-eex",
      revision = "f742f2fe327463335e8671a87c0b9b396905d1d1",
    },
    maintainers = { "@connorlay" },
  },
  ["elixir"] = {
    install_info = {
      url = "https://github.com/elixir-lang/tree-sitter-elixir",
      revision = "7937d3b4d65fa574163cfa59394515d3c1cf16f4",
    },
    maintainers = { "@connorlay" },
  },
  ["elm"] = {
    install_info = {
      url = "https://github.com/elm-tooling/tree-sitter-elm",
      revision = "6d9511c28181db66daee4e883f811f6251220943",
    },
    maintainers = { "@zweimach" },
  },
  ["elsa"] = {
    install_info = {
      url = "https://github.com/glapa-grossklag/tree-sitter-elsa",
      revision = "0a66b2b3f3c1915e67ad2ef9f7dbd2a84820d9d7",
    },
    maintainers = { "@glapa-grossklag", "@amaanq" },
  },
  ["elvish"] = {
    install_info = {
      url = "https://github.com/elves/tree-sitter-elvish",
      revision = "5e7210d945425b77f82cbaebc5af4dd3e1ad40f5",
    },
    maintainers = { "@elves" },
  },
  ["embedded_template"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-embedded-template",
      revision = "3499d85f0a0d937c507a4a65368f2f63772786e1",
    },
  },
  ["enforce"] = {
    install_info = {
      url = "https://github.com/simonvic/tree-sitter-enforce",
      revision = "eb2796871d966264cdb041b797416ef1757c8b4f",
    },
    maintainers = { "@simonvic" },
  },
  ["erlang"] = {
    install_info = {
      url = "https://github.com/WhatsApp/tree-sitter-erlang",
      revision = "1d78195c4fbb1fc027eb3e4220427f1eb8bfc89e",
    },
    maintainers = { "@filmor" },
  },
  ["facility"] = {
    install_info = {
      url = "https://github.com/FacilityApi/tree-sitter-facility",
      revision = "e4bfd3e960de9f4b4648acb1c92e9b95b47d8cfb",
    },
    maintainers = { "@bryankenote" },
  },
  ["faust"] = {
    install_info = {
      url = "https://github.com/khiner/tree-sitter-faust",
      revision = "122dd101919289ea809bad643712fcb483a1bed0",
    },
    maintainers = { "@khiner" },
  },
  ["fennel"] = {
    install_info = {
      url = "https://github.com/alexmozaidze/tree-sitter-fennel",
      revision = "3f0f6b24d599e92460b969aabc4f4c5a914d15a0",
    },
    maintainers = { "@alexmozaidze" },
  },
  ["fidl"] = {
    install_info = {
      url = "https://github.com/google/tree-sitter-fidl",
      revision = "0a8910f293268e27ff554357c229ba172b0eaed2",
    },
    maintainers = { "@chaopeng" },
  },
  ["firrtl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-firrtl",
      revision = "8503d3a0fe0f9e427863cb0055699ff2d29ae5f5",
    },
    maintainers = { "@amaanq" },
  },
  ["fish"] = {
    install_info = {
      url = "https://github.com/ram02z/tree-sitter-fish",
      revision = "fa2143f5d66a9eb6c007ba9173525ea7aaafe788",
    },
    maintainers = { "@ram02z" },
  },
  ["foam"] = {
    install_info = {
      url = "https://github.com/FoamScience/tree-sitter-foam",
      revision = "472c24f11a547820327fb1be565bcfff98ea96a4",
    },
    maintainers = { "@FoamScience" },
  },
  ["forth"] = {
    install_info = {
      url = "https://github.com/AlexanderBrevig/tree-sitter-forth",
      revision = "360ef13f8c609ec6d2e80782af69958b84e36cd0",
    },
    maintainers = { "@amaanq" },
  },
  ["fortran"] = {
    install_info = {
      url = "https://github.com/stadelmanma/tree-sitter-fortran",
      revision = "be30d90dc7dfa4080b9c4abed3f400c9163a88df",
    },
    maintainers = { "@amaanq" },
  },
  ["fsh"] = {
    install_info = {
      url = "https://github.com/mgramigna/tree-sitter-fsh",
      revision = "fad2e175099a45efbc98f000cc196d3674cc45e0",
    },
    maintainers = { "@mgramigna" },
  },
  ["fsharp"] = {
    install_info = {
      url = "https://github.com/ionide/tree-sitter-fsharp",
      location = "fsharp",
      revision = "1c2d9351d1f731c08cfdc4ed41e63126ae56e462",
    },
    maintainers = { "@nsidorenco" },
  },
  ["func"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-func",
      revision = "f780ca55e65e7d7360d0229331763e16c452fc98",
    },
    maintainers = { "@amaanq" },
  },
  ["gap"] = {
    install_info = {
      url = "https://github.com/gap-system/tree-sitter-gap",
      revision = "ed2480d42281586932920527823b307bc45052b8",
    },
    maintainers = { "@reiniscirpons" },
    readme_note = "GAP system",
  },
  ["gaptst"] = {
    install_info = {
      url = "https://github.com/gap-system/tree-sitter-gaptst",
      revision = "69086d7627c03e1f4baf766bcef14c60d9e92331",
    },
    maintainers = { "@reiniscirpons" },
    requires = { "gap" },
    readme_note = "GAP system test files",
  },
  ["gdscript"] = {
    install_info = {
      url = "https://github.com/PrestonKnopp/tree-sitter-gdscript",
      revision = "9686853b696db07118ad110e440d6de0ca6498b4",
    },
    readme_note = "Godot",
  },
  ["gdshader"] = {
    install_info = {
      url = "https://github.com/airblast-dev/tree-sitter-gdshader",
      revision = "68268631c8b6dc093985f1246b099f81b30ea7d1",
    },
    maintainers = { "@airblast-dev" },
  },
  ["ghostty"] = {
    install_info = {
      url = "https://github.com/bezhermoso/tree-sitter-ghostty",
    },
    maintainers = { "@bezhermoso" },
    readme_note = { "Ghostty configuration & theme files" },
  },
  ["git_config"] = {
    install_info = {
      url = "https://github.com/the-mikedavis/tree-sitter-git-config",
      revision = "0fbc9f99d5a28865f9de8427fb0672d66f9d83a5",
    },
    maintainers = { "@amaanq" },
  },
  ["git_rebase"] = {
    install_info = {
      url = "https://github.com/the-mikedavis/tree-sitter-git-rebase",
      revision = "760ba8e34e7a68294ffb9c495e1388e030366188",
    },
    maintainers = { "@gbprod" },
  },
  ["gitattributes"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-gitattributes",
      revision = "1b7af09d45b579f9f288453b95ad555f1f431645",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["gitcommit"] = {
    install_info = {
      url = "https://github.com/gbprod/tree-sitter-gitcommit",
      revision = "33fe8548abcc6e374feaac5724b5a2364bf23090",
    },
    maintainers = { "@gbprod" },
  },
  ["gitignore"] = {
    install_info = {
      url = "https://github.com/shunsambongi/tree-sitter-gitignore",
      revision = "f4685bf11ac466dd278449bcfe5fd014e94aa504",
    },
    maintainers = { "@theHamsta" },
  },
  ["gleam"] = {
    install_info = {
      url = "https://github.com/gleam-lang/tree-sitter-gleam",
      revision = "0bb1b0ae1a3555180ae7b0004851da747fc230d1",
    },
    maintainers = { "@amaanq" },
  },
  ["glimmer"] = {
    install_info = {
      url = "https://github.com/ember-tooling/tree-sitter-glimmer",
      revision = "88af85568bde3b91acb5d4c352ed094d0c1f9d84",
    },
    maintainers = { "@NullVoxPopuli" },
    readme_note = "Glimmer and Ember",
  },
  ["glimmer_javascript"] = {
    install_info = {
      url = "https://github.com/NullVoxPopuli/tree-sitter-glimmer-javascript",
      revision = "5cc865a2a0a77cbfaf5062c8fcf2a9919bd54f87",
    },
    maintainers = { "@NullVoxPopuli" },
    requires = { "ecma" },
  },
  ["glimmer_typescript"] = {
    install_info = {
      url = "https://github.com/NullVoxPopuli/tree-sitter-glimmer-typescript",
      revision = "12d98944c1d5077b957cbdb90d663a7c4d50118c",
    },
    maintainers = { "@NullVoxPopuli" },
    requires = { "typescript" },
  },
  ["glsl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-glsl",
      revision = "24a6c8ef698e4480fecf8340d771fbcb5de8fbb4",
    },
    maintainers = { "@theHamsta" },
    requires = { "c" },
  },
  ["gn"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-gn",
      revision = "bc06955bc1e3c9ff8e9b2b2a55b38b94da923c05",
    },
    maintainers = { "@amaanq" },
  },
  ["gnuplot"] = {
    install_info = {
      url = "https://github.com/dpezto/tree-sitter-gnuplot",
      revision = "8923c1e38b9634a688a6c0dce7c18c8ffb823e79",
    },
    maintainers = { "@dpezto" },
  },
  ["go"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-go",
      revision = "2346a3ab1bb3857b48b29d779a1ef9799a248cd7",
    },
    maintainers = { "@theHamsta", "@WinWisely268" },
  },
  ["goctl"] = {
    install_info = {
      url = "https://github.com/chaozwn/tree-sitter-goctl",
      revision = "49c43532689fe1f53e8b9e009d0521cab02c432b",
    },
    maintainers = { "@chaozwn" },
  },
  ["godot_resource"] = {
    install_info = {
      url = "https://github.com/PrestonKnopp/tree-sitter-godot-resource",
      revision = "302c1895f54bf74d53a08572f7b26a6614209adc",
    },
    maintainers = { "@pierpo" },
    readme_note = "Godot Resources",
  },
  ["gomod"] = {
    install_info = {
      url = "https://github.com/camdencheek/tree-sitter-go-mod",
      revision = "2e886870578eeba1927a2dc4bd2e2b3f598c5f9a",
    },
    maintainers = { "@camdencheek" },
  },
  ["gosum"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-go-sum",
      revision = "27816eb6b7315746ae9fcf711e4e1396dc1cf237",
    },
    maintainers = { "@amaanq" },
  },
  ["gotmpl"] = {
    install_info = {
      url = "https://github.com/ngalaiko/tree-sitter-go-template",
      revision = "aa71f63de226c5592dfbfc1f29949522d7c95fac",
    },
    maintainers = { "@qvalentin" },
  },
  ["gowork"] = {
    install_info = {
      url = "https://github.com/omertuc/tree-sitter-go-work",
      revision = "949a8a470559543857a62102c84700d291fc984c",
    },
    maintainers = { "@omertuc" },
  },
  ["gpg"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-gpg-config",
      revision = "4024eb268c59204280f8ac71ef146b8ff5e737f6",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["graphql"] = {
    install_info = {
      url = "https://github.com/bkegley/tree-sitter-graphql",
      revision = "5e66e961eee421786bdda8495ed1db045e06b5fe",
    },
    maintainers = { "@bkegley" },
  },
  ["gren"] = {
    install_info = {
      url = "https://github.com/MaeBrooks/tree-sitter-gren",
      revision = "c36aac51a915fdfcaf178128ba1e9c2205b25930",
    },
    maintainers = { "@MaeBrooks" },
  },
  ["groovy"] = {
    install_info = {
      url = "https://github.com/murtaza64/tree-sitter-groovy",
      revision = "781d9cd1b482a70a6b27091e5c9e14bbcab3b768",
    },
    maintainers = { "@murtaza64" },
  },
  ["groq"] = {
    install_info = {
      url = "https://github.com/ajrussellaudio/tree-sitter-groq",
      revision = "1fa1ab0eb391a270957e8ad8c731b492e3645649",
    },
    maintainers = { "@ajrussellaudio" },
  },
  ["gstlaunch"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-gstlaunch",
      revision = "549aef253fd38a53995cda1bf55c501174372bf7",
    },
    maintainers = { "@theHamsta" },
  },
  ["hack"] = {
    install_info = {
      url = "https://github.com/slackhq/tree-sitter-hack",
      revision = "1a7ded90288189746c54861ac144ede97df95081",
    },
  },
  ["hare"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-hare",
      revision = "eed7ddf6a66b596906aa8ca3d40521b8278adc6f",
    },
    maintainers = { "@amaanq" },
  },
  ["haskell"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-haskell",
      revision = "7fa19f195803a77855f036ee7f49e4b22856e338",
    },
    maintainers = { "@mrcjkb" },
  },
  ["haskell_persistent"] = {
    install_info = {
      url = "https://github.com/MercuryTechnologies/tree-sitter-haskell-persistent",
      revision = "577259b4068b2c281c9ebf94c109bd50a74d5857",
    },
    maintainers = { "@lykahb" },
  },
  ["hcl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-hcl",
      revision = "64ad62785d442eb4d45df3a1764962dafd5bc98b",
    },
    maintainers = { "@MichaHoffmann" },
  },
  ["heex"] = {
    install_info = {
      url = "https://github.com/connorlay/tree-sitter-heex",
      revision = "5842537f734d7c12685bf27d6005313e3e5a47a0",
    },
    maintainers = { "@connorlay" },
  },
  ["helm"] = {
    install_info = {
      url = "https://github.com/ngalaiko/tree-sitter-go-template",
      location = "dialects/helm",
      revision = "aa71f63de226c5592dfbfc1f29949522d7c95fac",
    },
    maintainers = { "@qvalentin" },
  },
  ["hjson"] = {
    install_info = {
      url = "https://github.com/winston0410/tree-sitter-hjson",
      revision = "02fa3b79b3ff9a296066da6277adfc3f26cbc9e0",
    },
    maintainers = { "@winston0410" },
    requires = { "json" },
  },
  ["hlsl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-hlsl",
      revision = "bab9111922d53d43668fabb61869bec51bbcb915",
    },
    maintainers = { "@theHamsta" },
    requires = { "cpp" },
  },
  ["hlsplaylist"] = {
    install_info = {
      url = "https://github.com/Freed-Wu/tree-sitter-hlsplaylist",
      revision = "3bfda9271e3adb08d35f47a2102fe957009e1c55",
    },
    maintainers = { "@Freed-Wu" },
  },
  ["hocon"] = {
    install_info = {
      url = "https://github.com/antosha417/tree-sitter-hocon",
      revision = "c390f10519ae69fdb03b3e5764f5592fb6924bcc",
    },
    maintainers = { "@antosha417" },
  },
  ["hoon"] = {
    install_info = {
      url = "https://github.com/urbit-pilled/tree-sitter-hoon",
      revision = "1545137aadcc63660c47db9ad98d02fa602655d0",
    },
    maintainers = { "@urbit-pilled" },
  },
  ["html"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-html",
      revision = "73a3947324f6efddf9e17c0ea58d454843590cc0",
    },
    maintainers = { "@TravonteD" },
    requires = { "html_tags" },
  },
  ["htmldjango"] = {
    install_info = {
      url = "https://github.com/interdependence/tree-sitter-htmldjango",
      revision = "3a643167ad9afac5d61e092f08ff5b054576fadf",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["http"] = {
    install_info = {
      url = "https://github.com/rest-nvim/tree-sitter-http",
      revision = "db8b4398de90b6d0b6c780aba96aaa2cd8e9202c",
    },
    maintainers = { "@amaanq", "@NTBBloodbath" },
  },
  ["hurl"] = {
    install_info = {
      url = "https://github.com/pfeiferj/tree-sitter-hurl",
      revision = "597efbd7ce9a814bb058f48eabd055b1d1e12145",
    },
    maintainers = { "@pfeiferj" },
  },
  ["hyprlang"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang",
      revision = "cecd6b748107d9da1f7b4ca03ef95f1f71d93b8f",
    },
    maintainers = { "@luckasRanarison" },
  },
  ["idl"] = {
    install_info = {
      url = "https://github.com/cathaysia/tree-sitter-idl",
      revision = "fb65762a13538b397e41a5fc1e9564c9df841410",
    },
    maintainers = { "@cathaysia" },
  },
  ["idris"] = {
    install_info = {
      url = "https://github.com/kayhide/tree-sitter-idris",
      revision = "c56a25cf57c68ff929356db25505c1cc4c7820f6",
    },
  },
  ["ini"] = {
    install_info = {
      url = "https://github.com/justinmk/tree-sitter-ini",
      revision = "e4018b5176132b4f3c5d6e61cea383f42288d0f5",
    },
    maintainers = { "@theHamsta" },
  },
  ["inko"] = {
    install_info = {
      url = "https://github.com/inko-lang/tree-sitter-inko",
      revision = "v0.5.1",
    },
    maintainers = { "@yorickpeterse" },
  },
  ["ispc"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-ispc",
      revision = "9b2f9aec2106b94b4e099fe75e73ebd8ae707c04",
    },
    maintainers = { "@fab4100" },
    requires = { "c" },
  },
  ["janet_simple"] = {
    install_info = {
      url = "https://github.com/sogaiu/tree-sitter-janet-simple",
      revision = "d183186995204314700be3e9e0a48053ea16b350",
    },
    maintainers = { "@sogaiu" },
  },
  ["java"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-java",
      revision = "e10607b45ff745f5f876bfa3e94fbcc6b44bdc11",
    },
    maintainers = { "@p00f" },
  },
  ["javadoc"] = {
    install_info = {
      url = "https://github.com/rmuir/tree-sitter-javadoc",
      revision = "e2f56b4d0df08f6ed5df8bae266f9e75b340a9ab",
    },
    maintainers = { "@rmuir" },
  },
  ["javascript"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-javascript",
      revision = "58404d8cf191d69f2674a8fd507bd5776f46cb11",
    },
    maintainers = { "@steelsojka" },
    requires = { "ecma", "jsx" },
  },
  ["jinja"] = {
    install_info = {
      url = "https://github.com/cathaysia/tree-sitter-jinja",
      location = "tree-sitter-jinja",
      revision = "413dba9fea354b62f6adada1815b2f504e32ffb5",
    },
    maintainers = { "@cathaysia" },
    requires = { "jinja_inline" },
    readme_note = "basic highlighting",
  },
  ["jinja_inline"] = {
    install_info = {
      url = "https://github.com/cathaysia/tree-sitter-jinja",
      location = "tree-sitter-jinja_inline",
      revision = "413dba9fea354b62f6adada1815b2f504e32ffb5",
    },
    maintainers = { "@cathaysia" },
    readme_note = "needed for full highlighting",
  },
  ["jjdescription"] = {
    install_info = {
      url = "https://github.com/ribru17/tree-sitter-jjdescription",
      revision = "v1.0.3",
    },
    maintainers = { "@ribru17" },
  },
  ["jq"] = {
    install_info = {
      url = "https://github.com/flurie/tree-sitter-jq",
      revision = "c204e36d2c3c6fce1f57950b12cabcc24e5cc4d9",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["jsdoc"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-jsdoc",
      revision = "658d18dcdddb75c760363faa4963427a7c6b52db",
    },
    maintainers = { "@steelsojka" },
  },
  ["json"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-json",
      revision = "001c28d7a29832b06b0e831ec77845553c89b56d",
    },
    maintainers = { "@steelsojka" },
  },
  ["json5"] = {
    install_info = {
      url = "https://github.com/Joakker/tree-sitter-json5",
      revision = "aa630ef48903ab99e406a8acd2e2933077cc34e1",
    },
    maintainers = { "@Joakker" },
  },
  ["jsonnet"] = {
    install_info = {
      url = "https://github.com/sourcegraph/tree-sitter-jsonnet",
      revision = "ddd075f1939aed8147b7aa67f042eda3fce22790",
    },
    maintainers = { "@nawordar" },
  },
  ["julia"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-julia",
      revision = "8454f266717232525ed03c7b09164b0404a03150",
    },
    maintainers = { "@clason" },
  },
  ["just"] = {
    install_info = {
      url = "https://github.com/IndianBoy42/tree-sitter-just",
      revision = "5685543a6e64f66335e25518c9ae8ffa1dae3d01",
    },
    maintainers = { "@Hubro" },
  },
  ["kcl"] = {
    install_info = {
      url = "https://github.com/kcl-lang/tree-sitter-kcl",
      revision = "b0b2eb38009e04035a6e266c7e11e541f3caab7c",
    },
    maintainers = { "@bertbaron" },
  },
  ["kconfig"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-kconfig",
      revision = "9ac99fe4c0c27a35dc6f757cef534c646e944881",
    },
    maintainers = { "@amaanq" },
  },
  ["kdl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-kdl",
      revision = "b37e3d58e5c5cf8d739b315d6114e02d42e66664",
    },
    maintainers = { "@amaanq" },
  },
  ["kitty"] = {
    install_info = {
      url = "https://github.com/OXY2DEV/tree-sitter-kitty",
      revision = "fa6ab3fd32d890a0217495c96b35761e6d2dcb5b",
    },
    maintainers = { "@OXY2DEV" },
  },
  ["kos"] = {
    install_info = {
      url = "https://github.com/kos-lang/tree-sitter-kos",
      revision = "03b261c1a78b71c38cf4616497f253c4a4ce118b",
    },
    maintainers = { "@cdragan" },
  },
  ["kotlin"] = {
    install_info = {
      url = "https://github.com/fwcd/tree-sitter-kotlin",
      revision = "93bfeee1555d2b1442d68c44b0afde2a3b069e46",
    },
  },
  ["koto"] = {
    install_info = {
      url = "https://github.com/koto-lang/tree-sitter-koto",
      revision = "f8b3f62c0eed185dca1559789e78759d4bee60e5",
    },
    maintainers = { "@irh" },
  },
  ["kusto"] = {
    install_info = {
      url = "https://github.com/Willem-J-an/tree-sitter-kusto",
      revision = "8353a1296607d6ba33db7c7e312226e5fc83e8ce",
    },
    maintainers = { "@Willem-J-an" },
  },
  ["lalrpop"] = {
    install_info = {
      url = "https://github.com/traxys/tree-sitter-lalrpop",
      revision = "27b0f7bb55b4cabd8f01a933d9ee6a49dbfc2192",
    },
    maintainers = { "@traxys" },
  },
  ["latex"] = {
    install_info = {
      url = "https://github.com/latex-lsp/tree-sitter-latex",
      generate = true,
      revision = "7e0ecdc02926c7b9b2e0c76003d4fe7b0944f957",
    },
    maintainers = { "@theHamsta", "@clason" },
  },
  ["ledger"] = {
    install_info = {
      url = "https://github.com/cbarrete/tree-sitter-ledger",
      revision = "22a1ab8195c1f6e808679f803007756fe7638c6f",
    },
    maintainers = { "@cbarrete" },
  },
  ["leo"] = {
    install_info = {
      url = "https://github.com/r001/tree-sitter-leo",
      revision = "6bc5564917edacd070afc4d33cf5e2e677831ea9",
    },
    maintainers = { "@r001" },
  },
  ["linkerscript"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-linkerscript",
      revision = "f99011a3554213b654985a4b0a65b3b032ec4621",
    },
    maintainers = { "@amaanq" },
  },
  ["liquid"] = {
    install_info = {
      url = "https://github.com/hankthetank27/tree-sitter-liquid",
      revision = "9566ca79911052919fce09d26f1f655b5e093857",
    },
    maintainers = { "@hankthetank27" },
  },
  ["liquidsoap"] = {
    install_info = {
      url = "https://github.com/savonet/tree-sitter-liquidsoap",
      revision = "0169d92b0a93e9f32289533ef23abdafca579e56",
    },
    maintainers = { "@toots" },
  },
  ["llvm"] = {
    install_info = {
      url = "https://github.com/benwilliamgraham/tree-sitter-llvm",
      revision = "2914786ae6774d4c4e25a230f4afe16aa68fe1c1",
    },
    maintainers = { "@benwilliamgraham" },
  },
  ["lua"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-lua",
      revision = "10fe0054734eec83049514ea2e718b2a56acd0c9",
    },
    maintainers = { "@muniftanjim" },
  },
  ["luadoc"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-luadoc",
      revision = "873612aadd3f684dd4e631bdf42ea8990c57634e",
    },
    maintainers = { "@amaanq" },
  },
  ["luap"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-luap",
      revision = "c134aaec6acf4fa95fe4aa0dc9aba3eacdbbe55a",
    },
    maintainers = { "@amaanq" },
    readme_note = "Lua patterns",
  },
  ["luau"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-luau",
      revision = "a8914d6c1fc5131f8e1c13f769fa704c9f5eb02f",
    },
    maintainers = { "@amaanq" },
    requires = { "lua" },
  },
  ["m68k"] = {
    install_info = {
      url = "https://github.com/grahambates/tree-sitter-m68k",
      revision = "e128454c2210c0e0c10b68fe45ddb8fee80182a3",
    },
    maintainers = { "@grahambates" },
  },
  ["make"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-make",
      revision = "70613f3d812cbabbd7f38d104d60a409c4008b43",
    },
    maintainers = { "@lewis6991" },
  },
  ["markdown"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-markdown",
      location = "tree-sitter-markdown",
      revision = "f969cd3ae3f9fbd4e43205431d0ae286014c05b5",
    },
    maintainers = { "@MDeiml" },
    requires = { "markdown_inline" },
    readme_note = "basic highlighting",
  },
  ["markdown_inline"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-markdown",
      location = "tree-sitter-markdown-inline",
      revision = "f969cd3ae3f9fbd4e43205431d0ae286014c05b5",
    },
    maintainers = { "@MDeiml" },
    readme_note = "needed for full highlighting",
  },
  ["matlab"] = {
    install_info = {
      url = "https://github.com/acristoffers/tree-sitter-matlab",
      revision = "c2390a59016f74e7d5f75ef09510768b4f30217e",
    },
    maintainers = { "@acristoffers" },
  },
  ["menhir"] = {
    install_info = {
      url = "https://github.com/Kerl13/tree-sitter-menhir",
      revision = "be8866a6bcc2b563ab0de895af69daeffa88fe70",
    },
    maintainers = { "@Kerl13" },
  },
  ["mermaid"] = {
    install_info = {
      url = "https://github.com/monaqa/tree-sitter-mermaid",
      revision = "90ae195b31933ceb9d079abfa8a3ad0a36fee4cc",
    },
  },
  ["meson"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-meson",
      revision = "c84f3540624b81fc44067030afce2ff78d6ede05",
    },
    maintainers = { "@Decodetalkers" },
  },
  ["mlir"] = {
    install_info = {
      url = "https://github.com/artagnon/tree-sitter-mlir",
      generate = true,
      revision = "96fa0adc3028cc6a9d281370c9f213a457c4a2d0",
    },
    maintainers = { "@artagnon" },
  },
  ["muttrc"] = {
    install_info = {
      url = "https://github.com/neomutt/tree-sitter-muttrc",
      revision = "173b0ab53a9c07962c9777189c4c70e90f1c1837",
    },
    maintainers = { "@Freed-Wu" },
  },
  ["nasm"] = {
    install_info = {
      url = "https://github.com/naclsn/tree-sitter-nasm",
      revision = "d1b3638d017f2a8585e26dcfc66fe1df94185e30",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["nginx"] = {
    install_info = {
      url = "https://github.com/opa-oz/tree-sitter-nginx",
      revision = "47ade644d754cce57974aac44d2c9450e823d4f4",
    },
    maintainers = { "@opa-oz" },
  },
  ["nickel"] = {
    install_info = {
      url = "https://github.com/nickel-lang/tree-sitter-nickel",
      revision = "b5b6cc3bc7b9ea19f78fed264190685419cd17a8",
    },
  },
  ["nim"] = {
    install_info = {
      url = "https://github.com/alaviss/tree-sitter-nim",
      revision = "3878440d9398515ae053c6f6024986e69868bb74",
    },
    maintainers = { "@aMOPel" },
    requires = { "nim_format_string" },
  },
  ["nim_format_string"] = {
    install_info = {
      url = "https://github.com/aMOPel/tree-sitter-nim-format-string",
      revision = "d45f75022d147cda056e98bfba68222c9c8eca3a",
    },
    maintainers = { "@aMOPel" },
  },
  ["ninja"] = {
    install_info = {
      url = "https://github.com/alemuller/tree-sitter-ninja",
      revision = "0a95cfdc0745b6ae82f60d3a339b37f19b7b9267",
    },
    maintainers = { "@alemuller" },
  },
  ["nix"] = {
    install_info = {
      url = "https://github.com/nix-community/tree-sitter-nix",
      revision = "eabf96807ea4ab6d6c7f09b671a88cd483542840",
    },
    maintainers = { "@leo60228", "@mrcjkb", "@zimbatm" },
  },
  ["nqc"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-nqc",
      revision = "14e6da1627aaef21d2b2aa0c37d04269766dcc1d",
    },
    maintainers = { "@amaanq" },
  },
  ["nu"] = {
    install_info = {
      url = "https://github.com/nushell/tree-sitter-nu",
      revision = "696d257f6b652edb50878a783b30ad7833dec49e",
    },
    maintainers = { "@abhisheksingh0x558" },
  },
  ["objc"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-objc",
      revision = "181a81b8f23a2d593e7ab4259981f50122909fda",
    },
    maintainers = { "@amaanq" },
    requires = { "c" },
  },
  ["objdump"] = {
    install_info = {
      url = "https://github.com/ColinKennedy/tree-sitter-objdump",
      revision = "28d3b2e25a0b1881d1b47ed1924ca276c7003d45",
    },
    maintainers = { "@ColinKennedy" },
  },
  ["ocaml"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-ocaml",
      location = "grammars/ocaml",
      revision = "5a979b3ec7f1fe990b8e8c4412294a0cf7228e45",
    },
    maintainers = { "@undu" },
  },
  ["ocaml_interface"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-ocaml",
      location = "grammars/interface",
      revision = "5a979b3ec7f1fe990b8e8c4412294a0cf7228e45",
    },
    maintainers = { "@undu" },
    requires = { "ocaml" },
  },
  ["ocamllex"] = {
    install_info = {
      url = "https://github.com/atom-ocaml/tree-sitter-ocamllex",
      generate = true,
      revision = "33722b8be73079946a7c6dd9598e3f57956ed36d",
    },
    maintainers = { "@undu" },
  },
  ["odin"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-odin",
      revision = "d2ca8efb4487e156a60d5bd6db2598b872629403",
    },
    maintainers = { "@amaanq" },
  },
  ["pascal"] = {
    install_info = {
      url = "https://github.com/Isopod/tree-sitter-pascal",
      revision = "042119eca2e18a60e56317fb06ee3ba5c32cb447",
    },
    maintainers = { "@Isopod" },
  },
  ["passwd"] = {
    install_info = {
      url = "https://github.com/ath3/tree-sitter-passwd",
      revision = "20239395eacdc2e0923a7e5683ad3605aee7b716",
    },
    maintainers = { "@amaanq" },
  },
  ["pem"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-pem",
      revision = "e525b177a229b1154fd81bc0691f943028d9e685",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["perl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-perl/tree-sitter-perl",
      generate = true,
      revision = "ea9667dc65a816acace002a2b1b099978785ca33",
    },
    maintainers = { "@RabbiVeesh", "@LeoNerd" },
  },
  ["php"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-php",
      location = "php",
      revision = "3f2465c217d0a966d41e584b42d75522f2a3149e",
    },
    maintainers = { "@tk-shirasaka", "@calebdw" },
    requires = { "php_only" },
    readme_note = "PHP with embedded HTML",
  },
  ["php_only"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-php",
      location = "php_only",
      revision = "3f2465c217d0a966d41e584b42d75522f2a3149e",
    },
    maintainers = { "@tk-shirasaka", "@calebdw" },
    readme_note = "PHP without embedded HTML",
  },
  ["phpdoc"] = {
    install_info = {
      url = "https://github.com/claytonrcarter/tree-sitter-phpdoc",
      revision = "12d50307e6c02e5f4f876fa6cf2edea1f7808c0d",
    },
    maintainers = { "@mikehaertl" },
  },
  ["pioasm"] = {
    install_info = {
      url = "https://github.com/leo60228/tree-sitter-pioasm",
      revision = "afece58efdb30440bddd151ef1347fa8d6f744a9",
    },
    maintainers = { "@leo60228" },
  },
  ["pkl"] = {
    install_info = {
      url = "https://github.com/apple/tree-sitter-pkl",
      revision = "f5beed1da8e5fc856a1a11e29a929d0b7cdcfe3c",
    },
    maintainers = { "@ribru17" },
  },
  ["po"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-po",
      revision = "bd860a0f57f697162bf28e576674be9c1500db5e",
    },
    maintainers = { "@amaanq" },
  },
  ["pod"] = {
    install_info = {
      url = "https://github.com/tree-sitter-perl/tree-sitter-pod",
      generate = true,
      revision = "57c606aa3373ba876d44113d13fe7bdc2c060723",
    },
    maintainers = { "@RabbiVeesh", "@LeoNerd" },
  },
  ["poe_filter"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-poe-filter",
      revision = "205a7d576984feb38a9fc2d8cfe729617f9e0548",
    },
    maintainers = { "@ObserverOfTime" },
    readme_note = "Path of Exile item filter",
  },
  ["pony"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-pony",
      revision = "73ff874ae4c9e9b45462673cbc0a1e350e2522a7",
    },
    maintainers = { "@amaanq", "@mfelsche" },
  },
  ["powershell"] = {
    install_info = {
      url = "https://github.com/airbus-cert/tree-sitter-powershell",
      revision = "73800ecc8bddeee8f1079a5a2e0c13c3d00269bb",
    },
    maintainers = { "@L2jLiga" },
  },
  ["printf"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-printf",
      revision = "ec4e5674573d5554fccb87a887c97d4aec489da7",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["prisma"] = {
    install_info = {
      url = "https://github.com/victorhqc/tree-sitter-prisma",
      revision = "3556b2c1f20ec9ac91e92d32c43d9d2a0ca3cc49",
    },
    maintainers = { "@elianiva" },
  },
  ["problog"] = {
    install_info = {
      url = "https://github.com/foxyseta/tree-sitter-prolog",
      location = "grammars/problog",
      revision = "d8d415f6a1cf80ca138524bcc395810b176d40fa",
    },
    maintainers = { "@foxyseta" },
    requires = { "prolog" },
  },
  ["prolog"] = {
    install_info = {
      url = "https://github.com/foxyseta/tree-sitter-prolog",
      location = "grammars/prolog",
      revision = "d8d415f6a1cf80ca138524bcc395810b176d40fa",
    },
    maintainers = { "@foxyseta" },
  },
  ["promql"] = {
    install_info = {
      url = "https://github.com/MichaHoffmann/tree-sitter-promql",
      revision = "77625d78eebc3ffc44d114a07b2f348dff3061b0",
    },
    maintainers = { "@MichaHoffmann" },
  },
  ["properties"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-properties",
      revision = "6310671b24d4e04b803577b1c675d765cbd5773b",
    },
    maintainers = { "@ObserverOfTime" },
    readme_note = "Java properties files",
  },
  ["proto"] = {
    install_info = {
      url = "https://github.com/coder3101/tree-sitter-proto",
      revision = "d65a18ce7c2242801f702770114ad08056c7f8c9",
    },
    maintainers = { "@stefanvanburen" },
  },
  ["prql"] = {
    install_info = {
      url = "https://github.com/PRQL/tree-sitter-prql",
      revision = "09e158cd3650581c0af4c49c2e5b10c4834c8646",
    },
    maintainers = { "@matthias-Q" },
  },
  ["psv"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-csv",
      location = "psv",
      revision = "f6bf6e35eb0b95fbadea4bb39cb9709507fcb181",
    },
    maintainers = { "@amaanq" },
    requires = { "tsv" },
  },
  ["pug"] = {
    install_info = {
      url = "https://github.com/zealot128/tree-sitter-pug",
      revision = "13e9195370172c86a8b88184cc358b23b677cc46",
    },
    maintainers = { "@zealot128" },
  },
  ["puppet"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-puppet",
      revision = "15f192929b7d317f5914de2b4accd37b349182a6",
    },
    maintainers = { "@amaanq" },
  },
  ["purescript"] = {
    install_info = {
      url = "https://github.com/postsolar/tree-sitter-purescript",
      revision = "f541f95ffd6852fbbe88636317c613285bc105af",
    },
    maintainers = { "@postsolar" },
  },
  ["pymanifest"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-pymanifest",
      revision = "debbdb83fe6356adc7261c41c69b45ba49c97294",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["python"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-python",
      revision = "710796b8b877a970297106e5bbc8e2afa47f86ec",
    },
    maintainers = { "@stsewd", "@theHamsta" },
  },
  ["ql"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-ql",
      revision = "1fd627a4e8bff8c24c11987474bd33112bead857",
    },
    maintainers = { "@pwntester" },
  },
  ["qmldir"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-qmldir",
      revision = "6b2b5e41734bd6f07ea4c36ac20fb6f14061c841",
    },
    maintainers = { "@amaanq" },
  },
  ["qmljs"] = {
    install_info = {
      url = "https://github.com/yuja/tree-sitter-qmljs",
      revision = "0bec4359a7eb2f6c9220cd57372d87d236f66d59",
    },
    maintainers = { "@Decodetalkers" },
    requires = { "ecma" },
  },
  ["query"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-query",
      revision = "fc5409c6820dd5e02b0b0a309d3da2bfcde2db17",
    },
    maintainers = { "@steelsojka" },
    readme_note = "Tree-sitter query language",
  },
  ["r"] = {
    install_info = {
      url = "https://github.com/r-lib/tree-sitter-r",
      revision = "0e6ef7741712c09dc3ee6e81c42e919820cc65ef",
    },
    maintainers = { "@ribru17" },
  },
  ["racket"] = {
    install_info = {
      url = "https://github.com/6cdh/tree-sitter-racket",
      revision = "54649be8b939341d2d5410b594ab954fe8814bd0",
    },
  },
  ["ralph"] = {
    install_info = {
      url = "https://github.com/alephium/tree-sitter-ralph",
      revision = "f6d81bf7a4599c77388035439cf5801cd461ff77",
    },
    maintainers = { "@tdroxler" },
  },
  ["rasi"] = {
    install_info = {
      url = "https://github.com/Fymyte/tree-sitter-rasi",
      revision = "e735c6881d8b475aaa4ef8f0a2bdfd825b438143",
    },
    maintainers = { "@Fymyte" },
  },
  ["razor"] = {
    install_info = {
      url = "https://github.com/tris203/tree-sitter-razor",
      revision = "fe46ce5ea7d844e53d59bc96f2175d33691c61c5",
    },
    maintainers = { "@tris203" },
  },
  ["rbs"] = {
    install_info = {
      url = "https://github.com/joker1007/tree-sitter-rbs",
      revision = "5282e2f36d4109f5315c1d9486b5b0c2044622bb",
    },
    maintainers = { "@joker1007" },
  },
  ["re2c"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-re2c",
      revision = "c18a3c2f4b6665e35b7e50d6048ea3cff770c572",
    },
    maintainers = { "@amaanq" },
  },
  ["readline"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-readline",
      revision = "6b744c527aebd12e46a5ecb3aebdb8d621a8e83e",
    },
    maintainers = { "@ribru17" },
  },
  ["regex"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-regex",
      revision = "b2ac15e27fce703d2f37a79ccd94a5c0cbe9720b",
    },
    maintainers = { "@theHamsta" },
  },
  ["rego"] = {
    install_info = {
      url = "https://github.com/FallenAngel97/tree-sitter-rego",
      revision = "ddd39af81fe8b0288102a7cb97959dfce723e0f3",
    },
    maintainers = { "@FallenAngel97" },
  },
  ["requirements"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-requirements",
      revision = "caeb2ba854dea55931f76034978de1fd79362939",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["rescript"] = {
    install_info = {
      url = "https://github.com/rescript-lang/tree-sitter-rescript",
      revision = "43c2f1f35024918d415dc933d4cc534d6419fedf",
    },
    maintainers = { "@ribru17" },
  },
  ["rifleconf"] = {
    install_info = {
      url = "https://github.com/purarue/tree-sitter-rifleconf",
      revision = "6389ef0fc0d48f0397ec233109c074a0cb685e36",
    },
    maintainers = { "@purarue" },
  },
  ["rnoweb"] = {
    install_info = {
      url = "https://github.com/bamonroe/tree-sitter-rnoweb",
      revision = "1a74dc0ed731ad07db39f063e2c5a6fe528cae7f",
    },
    maintainers = { "@bamonroe" },
  },
  ["robot"] = {
    install_info = {
      url = "https://github.com/Hubro/tree-sitter-robot",
      revision = "v1.3.0",
    },
  },
  ["robots_txt"] = {
    install_info = {
      url = "https://github.com/opa-oz/tree-sitter-robots-txt",
      revision = "0c066107e3548de79316a6a4ec771e2f7cf7c468",
    },
    maintainers = { "@opa-oz" },
  },
  ["roc"] = {
    install_info = {
      url = "https://github.com/faldor20/tree-sitter-roc",
      revision = "40e52f343f1b1f270d6ecb2ca898ca9b8cba6936",
    },
  },
  ["ron"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-ron",
      revision = "78938553b93075e638035f624973083451b29055",
    },
    maintainers = { "@amaanq" },
  },
  ["rst"] = {
    install_info = {
      url = "https://github.com/stsewd/tree-sitter-rst",
      revision = "4e562e1598b95b93db4f3f64fe40ddefbc677a15",
    },
    maintainers = { "@stsewd" },
  },
  ["ruby"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-ruby",
      revision = "ad907a69da0c8a4f7a943a7fe012712208da6dee",
    },
    maintainers = { "@TravonteD" },
  },
  ["runescript"] = {
    install_info = {
      url = "https://github.com/2004Scape/tree-sitter-runescript",
      revision = "cf85bbd5da0c5ad243301d889c7f84d790a4cae4",
    },
    maintainers = { "@2004Scape" },
  },
  ["rust"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-rust",
      revision = "77a3747266f4d621d0757825e6b11edcbf991ca5",
    },
    maintainers = { "@amaanq" },
  },
  ["scala"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-scala",
      revision = "14c5cfd2b8e0f057ba0f4f72ee4812b0ae6cdce3",
    },
    maintainers = { "@stevanmilic" },
  },
  ["scfg"] = {
    install_info = {
      url = "https://github.com/rockorager/tree-sitter-scfg",
      revision = "d850fd470445d73de318a21d734d1e09e29b773c",
    },
    maintainers = { "@WhyNotHugo" },
  },
  ["scheme"] = {
    install_info = {
      url = "https://github.com/6cdh/tree-sitter-scheme",
      revision = "c6cb7c7d7a04b3f5d999c28e2e9c0c31b2d50ece",
    },
  },
  ["scss"] = {
    install_info = {
      url = "https://github.com/serenadeai/tree-sitter-scss",
      revision = "c478c6868648eff49eb04a4df90d703dc45b312a",
    },
    maintainers = { "@elianiva" },
    requires = { "css" },
  },
  ["sflog"] = {
    install_info = {
      url = "https://github.com/aheber/tree-sitter-sfapex",
      location = "sflog",
      revision = "3597575a429766dd7ecce9f5bb97f6fec4419d5d",
    },
    maintainers = { "@aheber", "@xixiaofinland" },
    readme_note = "Salesforce debug log",
  },
  ["slang"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-slang",
      revision = "1dbcc4abc7b3cdd663eb03d93031167d6ed19f56",
    },
    maintainers = { "@theHamsta" },
    readme_note = "Shader Slang",
  },
  ["slim"] = {
    install_info = {
      url = "https://github.com/theoo/tree-sitter-slim",
      revision = "a06113f5175b805a37d20df0a6f9d722e0ab6cfe",
    },
    maintainers = { "@theoo" },
  },
  ["slint"] = {
    install_info = {
      url = "https://github.com/slint-ui/tree-sitter-slint",
      revision = "4d7ad0617c30f865f051bbac04a9826bea29f987",
    },
    maintainers = { "@hunger" },
  },
  ["smali"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-smali",
      revision = "fdfa6a1febc43c7467aa7e937b87b607956f2346",
    },
    maintainers = { "@amaanq" },
  },
  ["smithy"] = {
    install_info = {
      url = "https://github.com/indoorvivants/tree-sitter-smithy",
      revision = "ec4fe14586f2b0a1bc65d6db17f8d8acd8a90433",
    },
    maintainers = { "@amaanq", "@keynmol" },
  },
  ["snakemake"] = {
    install_info = {
      url = "https://github.com/osthomas/tree-sitter-snakemake",
      revision = "68010430c3e51c0e84c1ce21c6551df0e2469f51",
    },
    maintainers = { "@osthomas" },
  },
  ["snl"] = {
    install_info = {
      url = "https://github.com/minijackson/tree-sitter-snl",
      revision = "846e2d6809ac5863a15b5494f20fd267c21221c8",
    },
    maintainers = { "@minijackson" },
    readme_note = "EPICS Sequencer's SNL files",
  },
  ["solidity"] = {
    install_info = {
      url = "https://github.com/JoranHonig/tree-sitter-solidity",
      revision = "048fe686cb1fde267243739b8bdbec8fc3a55272",
    },
    maintainers = { "@amaanq" },
  },
  ["soql"] = {
    install_info = {
      url = "https://github.com/aheber/tree-sitter-sfapex",
      location = "soql",
      revision = "3597575a429766dd7ecce9f5bb97f6fec4419d5d",
    },
    maintainers = { "@aheber", "@xixiafinland" },
  },
  ["sosl"] = {
    install_info = {
      url = "https://github.com/aheber/tree-sitter-sfapex",
      location = "sosl",
      revision = "3597575a429766dd7ecce9f5bb97f6fec4419d5d",
    },
    maintainers = { "@aheber", "@xixiafinland" },
  },
  ["sourcepawn"] = {
    install_info = {
      url = "https://github.com/nilshelmig/tree-sitter-sourcepawn",
      revision = "5a8fdd446b516c81e218245c12129c6ad4bccfa2",
    },
    maintainers = { "@Sarrus1" },
  },
  ["sparql"] = {
    install_info = {
      url = "https://github.com/GordianDziwis/tree-sitter-sparql",
      revision = "1ef52d35a73a2a5f2e433ecfd1c751c1360a923b",
    },
    maintainers = { "@GordianDziwis" },
  },
  ["sproto"] = {
    install_info = {
      url = "https://github.com/hanxi/tree-sitter-sproto",
      revision = "d554c1456e35e7b2690552d52921c987d0cf6799",
    },
    maintainers = { "@hanxi" },
  },
  ["sql"] = {
    install_info = {
      url = "https://github.com/derekstride/tree-sitter-sql",
      branch = "gh-pages",
      revision = "851e9cb257ba7c66cc8c14214a31c44d2f1e954e",
    },
    maintainers = { "@derekstride" },
  },
  ["squirrel"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-squirrel",
      revision = "072c969749e66f000dba35a33c387650e203e96e",
    },
    maintainers = { "@amaanq" },
  },
  ["ssh_config"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-ssh-config",
      revision = "71d2693deadaca8cdc09e38ba41d2f6042da1616",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["starlark"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-starlark",
      revision = "a453dbf3ba433db0e5ec621a38a7e59d72e4dc69",
    },
    maintainers = { "@amaanq" },
  },
  ["strace"] = {
    install_info = {
      url = "https://github.com/sigmaSd/tree-sitter-strace",
      revision = "ac874ddfcc08d689fee1f4533789e06d88388f29",
    },
    maintainers = { "@amaanq" },
  },
  ["styled"] = {
    install_info = {
      url = "https://github.com/mskelton/tree-sitter-styled",
      revision = "319cdcaa0346ba6db668a222d938e5c3569e2a51",
    },
    maintainers = { "@mskelton" },
  },
  ["supercollider"] = {
    install_info = {
      url = "https://github.com/madskjeldgaard/tree-sitter-supercollider",
      revision = "2b03ff49dd19b046add072d0861c4d1ca8a384c8",
    },
    maintainers = { "@madskjeldgaard", "@elgiano" },
  },
  ["superhtml"] = {
    install_info = {
      url = "https://github.com/kristoff-it/superhtml",
      location = "tree-sitter-superhtml",
      revision = "8b5bb272b269afdd38cdf641c4a707dd92fbe902",
    },
    maintainers = { "@rockorager" },
  },
  ["surface"] = {
    install_info = {
      url = "https://github.com/connorlay/tree-sitter-surface",
      revision = "f4586b35ac8548667a9aaa4eae44456c1f43d032",
    },
    maintainers = { "@connorlay" },
  },
  ["svelte"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-svelte",
      revision = "ae5199db47757f785e43a14b332118a5474de1a2",
    },
    maintainers = { "@amaanq" },
    requires = { "html_tags" },
  },
  ["sway"] = {
    install_info = {
      url = "https://github.com/FuelLabs/tree-sitter-sway",
      revision = "9b7845ce06ecb38b040c3940970b4fd0adc331d1",
    },
    maintainers = { "@ribru17" },
  },
  ["swift"] = {
    install_info = {
      url = "https://github.com/alex-pinkus/tree-sitter-swift",
      generate = true,
      revision = "8abb3e8b33256d89127a35e87480736f74755ff9",
    },
    maintainers = { "@alex-pinkus" },
  },
  ["sxhkdrc"] = {
    install_info = {
      url = "https://github.com/RaafatTurki/tree-sitter-sxhkdrc",
      revision = "440d5f913d9465c9c776a1bd92334d32febcf065",
    },
    maintainers = { "@RaafatTurki" },
  },
  ["systemtap"] = {
    install_info = {
      url = "https://github.com/ok-ryoko/tree-sitter-systemtap",
      revision = "f2b378a9af0b7e1192cff67a5fb45508c927205d",
    },
    maintainers = { "@ok-ryoko" },
  },
  ["systemverilog"] = {
    install_info = {
      url = "https://github.com/gmlarumbe/tree-sitter-systemverilog",
      revision = "293928578cb27fbd0005fcc5f09c09a1e8628c89",
    },
    maintainers = { "@zhangwwpeng" },
  },
  ["t32"] = {
    install_info = {
      url = "https://github.com/xasc/tree-sitter-t32",
      revision = "3bce3977303c3f88bfa9fcdfcfd1a4f8f6ffa0b0",
    },
    maintainers = { "@xasc" },
  },
  ["tablegen"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-tablegen",
      revision = "b1170880c61355aaf38fc06f4af7d3c55abdabc4",
    },
    maintainers = { "@amaanq" },
  },
  ["tact"] = {
    install_info = {
      url = "https://github.com/tact-lang/tree-sitter-tact",
      revision = "a6267c2091ed432c248780cec9f8d42c8766d9ad",
    },
    maintainers = { "@novusnota" },
  },
  ["tcl"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-tcl",
      revision = "8f11ac7206a54ed11210491cee1e0657e2962c47",
    },
    maintainers = { "@lewis6991" },
  },
  ["teal"] = {
    install_info = {
      url = "https://github.com/euclidianAce/tree-sitter-teal",
      generate = true,
      revision = "05d276e737055e6f77a21335b7573c9d3c091e2f",
    },
    maintainers = { "@euclidianAce" },
  },
  ["templ"] = {
    install_info = {
      url = "https://github.com/vrischmann/tree-sitter-templ",
      revision = "1c6db04effbcd7773c826bded9783cbc3061bd55",
    },
    maintainers = { "@vrischmann" },
  },
  ["tera"] = {
    install_info = {
      url = "https://github.com/uncenter/tree-sitter-tera",
      revision = "3a38c368e806268daac9923a27e72bcafbbc16bb",
    },
    maintainers = { "@uncenter" },
  },
  ["terraform"] = {
    install_info = {
      url = "https://github.com/MichaHoffmann/tree-sitter-hcl",
      location = "dialects/terraform",
      revision = "64ad62785d442eb4d45df3a1764962dafd5bc98b",
    },
    maintainers = { "@MichaHoffmann" },
    requires = { "hcl" },
  },
  ["textproto"] = {
    install_info = {
      url = "https://github.com/PorterAtGoogle/tree-sitter-textproto",
      revision = "568471b80fd8793d37ed01865d8c2208a9fefd1b",
    },
    maintainers = { "@Porter" },
  },
  ["thrift"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-thrift",
      revision = "68fd0d80943a828d9e6f49c58a74be1e9ca142cf",
    },
    maintainers = { "@amaanq", "@duskmoon314" },
  },
  ["tiger"] = {
    install_info = {
      url = "https://github.com/ambroisie/tree-sitter-tiger",
      revision = "4a77b2d7a004587646bddc4e854779044b6db459",
    },
    maintainers = { "@ambroisie" },
  },
  ["tlaplus"] = {
    install_info = {
      url = "https://github.com/tlaplus-community/tree-sitter-tlaplus",
      revision = "add40814fda369f6efd989977b2c498aaddde984",
    },
    maintainers = { "@ahelwer", "@susliko" },
  },
  ["tmux"] = {
    install_info = {
      url = "https://github.com/Freed-Wu/tree-sitter-tmux",
      revision = "75d1b995b0c23400ac8e49db757a2e0386f9fa8f",
    },
    maintainers = { "@Freed-Wu", "@stevenxxiu" },
  },
  ["todotxt"] = {
    install_info = {
      url = "https://github.com/arnarg/tree-sitter-todotxt",
      revision = "3937c5cd105ec4127448651a21aef45f52d19609",
    },
    maintainers = { "@arnarg" },
  },
  ["toml"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-toml",
      revision = "64b56832c2cffe41758f28e05c756a3a98d16f41",
    },
    maintainers = { "@tk-shirasaka" },
  },
  ["tsv"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-csv",
      location = "tsv",
      revision = "f6bf6e35eb0b95fbadea4bb39cb9709507fcb181",
    },
    maintainers = { "@amaanq" },
  },
  ["tsx"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-typescript",
      location = "tsx",
      revision = "75b3874edb2dc714fb1fd77a32013d0f8699989f",
    },
    maintainers = { "@steelsojka" },
    requires = { "ecma", "jsx", "typescript" },
  },
  ["turtle"] = {
    install_info = {
      url = "https://github.com/GordianDziwis/tree-sitter-turtle",
      revision = "7f789ea7ef765080f71a298fc96b7c957fa24422",
    },
    maintainers = { "@GordianDziwis" },
  },
  ["twig"] = {
    install_info = {
      url = "https://github.com/gbprod/tree-sitter-twig",
      revision = "7195ee573ab5c3b3bb0e91b042e6f83ac1b11104",
    },
    maintainers = { "@gbprod" },
  },
  ["typescript"] = {
    install_info = {
      url = "https://github.com/tree-sitter/tree-sitter-typescript",
      location = "typescript",
      revision = "75b3874edb2dc714fb1fd77a32013d0f8699989f",
    },
    maintainers = { "@steelsojka" },
    requires = { "ecma" },
  },
  ["typespec"] = {
    install_info = {
      url = "https://github.com/happenslol/tree-sitter-typespec",
      revision = "395bef1e1eb4dd18365401642beb534e8a244056",
    },
    maintainers = { "@happenslol" },
  },
  ["typoscript"] = {
    install_info = {
      url = "https://github.com/Teddytrombone/tree-sitter-typoscript",
      revision = "b5d0162b328ec52cf300054a8a23d47f84f55cb4",
    },
    maintainers = { "@Teddytrombone" },
  },
  ["typst"] = {
    install_info = {
      url = "https://github.com/uben0/tree-sitter-typst",
      revision = "46cf4ded12ee974a70bf8457263b67ad7ee0379d",
    },
    maintainers = { "@uben0", "@RaafatTurki" },
  },
  ["udev"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-udev",
      revision = "2fcb563a4d56a6b8e8c129252325fc6335e4acbf",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["ungrammar"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-ungrammar",
      revision = "debd26fed283d80456ebafa33a06957b0c52e451",
    },
    maintainers = { "@Philipp-M", "@amaanq" },
  },
  ["unison"] = {
    install_info = {
      url = "https://github.com/kylegoetz/tree-sitter-unison",
      generate = true,
      revision = "10365cc70ab2b2de85ea7ab35cf6b7636c36ce8b",
    },
    maintainers = { "@tapegram" },
  },
  ["usd"] = {
    install_info = {
      url = "https://github.com/ColinKennedy/tree-sitter-usd",
      revision = "4e0875f724d94d0c2ff36f9b8cb0b12f8b20d216",
    },
    maintainers = { "@ColinKennedy" },
  },
  ["uxntal"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-uxntal",
      revision = "ad9b638b914095320de85d59c49ab271603af048",
    },
    maintainers = { "@amaanq" },
  },
  ["v"] = {
    install_info = {
      url = "https://github.com/vlang/v-analyzer",
      location = "tree_sitter_v",
      revision = "095865df4b9ddd21e376d635586c663d5a736f71",
    },
    maintainers = { "@kkharji", "@amaanq" },
  },
  ["vala"] = {
    install_info = {
      url = "https://github.com/vala-lang/tree-sitter-vala",
      revision = "97e6db3c8c73b15a9541a458d8e797a07f588ef4",
    },
    maintainers = { "@Prince781" },
  },
  ["vento"] = {
    install_info = {
      url = "https://github.com/ventojs/tree-sitter-vento",
      revision = "edd6596d4b0f392b87fc345dc26d84a6c32f7059",
    },
  },
  ["vhdl"] = {
    install_info = {
      url = "https://github.com/jpt13653903/tree-sitter-vhdl",
      revision = "c2d9be3d5ab7fb2cae8ad5ae604cd3606a4af0f2",
    },
    maintainers = { "@jpt13653903" },
  },
  ["vhs"] = {
    install_info = {
      url = "https://github.com/charmbracelet/tree-sitter-vhs",
      revision = "0c6fae9d2cfc5b217bfd1fe84a7678f5917116db",
    },
    maintainers = { "@caarlos0" },
  },
  ["vim"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-vim",
      revision = "3092fcd99eb87bbd0fc434aa03650ba58bd5b43b",
    },
    maintainers = { "@clason" },
  },
  ["vimdoc"] = {
    install_info = {
      url = "https://github.com/neovim/tree-sitter-vimdoc",
      revision = "f061895a0eff1d5b90e4fb60d21d87be3267031a",
    },
    maintainers = { "@clason" },
  },
  ["vrl"] = {
    install_info = {
      url = "https://github.com/belltoy/tree-sitter-vrl",
      revision = "274b3ce63f72aa8ffea18e7fc280d3062d28f0ba",
    },
    maintainers = { "@belltoy" },
  },
  ["vue"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-vue",
      revision = "ce8011a414fdf8091f4e4071752efc376f4afb08",
    },
    maintainers = { "@WhyNotHugo", "@lucario387" },
    requires = { "html_tags" },
  },
  ["wgsl"] = {
    install_info = {
      url = "https://github.com/szebniok/tree-sitter-wgsl",
      revision = "40259f3c77ea856841a4e0c4c807705f3e4a2b65",
    },
    maintainers = { "@szebniok" },
  },
  ["wgsl_bevy"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-wgsl-bevy",
      revision = "d9306a798ede627001a8e5752f775858c8edd7e4",
    },
    maintainers = { "@theHamsta" },
  },
  ["wing"] = {
    install_info = {
      url = "https://github.com/winglang/tree-sitter-wing",
      revision = "76e0c25844a66ebc6e866d690fcc5f4e90698947",
    },
    maintainers = { "@gshpychka", "@MarkMcCulloh" },
  },
  ["wit"] = {
    install_info = {
      url = "https://github.com/bytecodealliance/tree-sitter-wit",
      revision = "v1.3.0",
    },
    maintainers = { "@mkatychev" },
  },
  ["wxml"] = {
    install_info = {
      url = "https://github.com/BlockLune/tree-sitter-wxml",
      revision = "7b821c748dc410332f59496c0dea2632168c4e5a",
    },
    maintainers = { "@BlockLune" },
  },
  ["xcompose"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-xcompose",
      revision = "a51d6366f041dbefec4da39a7eb3168a9b1cbc0e",
    },
    maintainers = { "@ObserverOfTime" },
  },
  ["xml"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-xml",
      location = "xml",
      revision = "5000ae8f22d11fbe93939b05c1e37cf21117162d",
    },
    maintainers = { "@ObserverOfTime" },
    requires = { "dtd" },
  },
  ["xresources"] = {
    install_info = {
      url = "https://github.com/ValdezFOmar/tree-sitter-xresources",
      revision = "v1.0.0",
    },
    maintainers = { "@ValdezFOmar" },
  },
  ["yaml"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-yaml",
      revision = "4463985dfccc640f3d6991e3396a2047610cf5f8",
    },
    maintainers = { "@amaanq" },
  },
  ["yang"] = {
    install_info = {
      url = "https://github.com/Hubro/tree-sitter-yang",
      revision = "2c0e6be8dd4dcb961c345fa35c309ad4f5bd3502",
    },
    maintainers = { "@Hubro" },
  },
  ["yuck"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-yuck",
      revision = "6c60112b3b3e739fb1ca4a8ea4bea2b6ffe11318",
    },
    maintainers = { "@Philipp-M", "@amaanq" },
  },
  ["zathurarc"] = {
    install_info = {
      url = "https://github.com/Freed-Wu/tree-sitter-zathurarc",
      revision = "0554b4a5d313244b7fc000cbb41c04afae4f4e31",
    },
    maintainers = { "@Freed-Wu" },
  },
  ["zig"] = {
    install_info = {
      url = "https://github.com/tree-sitter-grammars/tree-sitter-zig",
      revision = "6479aa13f32f701c383083d8b28360ebd682fb7d",
    },
    maintainers = { "@amaanq" },
  },
  ["ziggy"] = {
    install_info = {
      url = "https://github.com/kristoff-it/ziggy",
      location = "tree-sitter-ziggy",
      revision = "4353b20ef2ac750e35c6d68e4eb2a07c2d7cf901",
    },
  },
  ["ziggy_schema"] = {
    install_info = {
      url = "https://github.com/kristoff-it/ziggy",
      location = "tree-sitter-ziggy-schema",
      revision = "4353b20ef2ac750e35c6d68e4eb2a07c2d7cf901",
    },
  },
  ["zsh"] = {
    install_info = {
      url = "https://github.com/georgeharker/tree-sitter-zsh",
      revision = "bd344c23a7683e293d077c6648e88f209782fedb",
    },
    maintainers = { "@georgeharker" },
  },
}
